### ISSUE TITLE
Self Dependent Server

### ISSUE THREAD

**Issue by Helixable** [netptop/siteproxy#1]
I gotthe server working, but when I try to access youtube videos, it leads to siteproxy.now.sh. It wont use my own server.

**Comment by netptop** [comment]
did you modify your serverName as required in deployment steps?

**Comment by Helixable** [comment]
`
let config = {
    httpprefix: 'https', 
    port: 443,
    serverName: 'siteproxy.now.sh',
}
`

Should I change this? If I change it to my server, it still doesn't work.

**Comment by Helixable** [comment]
This is what I changed it to 
```
let config = {
    'httpprefix' : 'https',
    'port' : '8080',
    'serverName' : 'poxe.helixable.repl.co' //Test server
}
```

**Comment by Helixable** [comment]
Nevermind. I got it to work. Thanks!
