### ISSUE TITLE
能不能去掉浏览器上那一行英文提醒，真的太烦了。

### ISSUE THREAD

**Issue by leeseed1** [netptop/siteproxy#103]
如题

**Comment by netptop** [comment]
确实，但是因为被人投诉，惹上官司，不得已的做法，避免有人上当，将个人信息泄漏。 

有什么两全其美的建议吗？

**Comment by leeseed1** [comment]
原来是这样，大佬辛苦了。如果可以的话，在下面提供一个没有警示的下载链接，或者告诉我删除哪里即可。谢谢了

**Comment by SunsetMkt** [comment]
> 确实，但是因为被人投诉，惹上官司，不得已的做法，避免有人上当，将个人信息泄漏。
> 
> 有什么两全其美的建议吗？

仅在第一次访问时提示？

**Comment by leeseed1** [comment]
> > 确实，但是因为被人投诉，惹上官司，不得已的做法，避免有人上当，将个人信息泄漏。
> > 
> > 有什么两全其美的建议吗？
> 
> 仅在第一次访问时提示？或者修改`_0x27**cc`。

把这个参数修改成什么？还是把什么参数修改成这个？

**Comment by netptop** [comment]
> > 确实，但是因为被人投诉，惹上官司，不得已的做法，避免有人上当，将个人信息泄漏。
> > 有什么两全其美的建议吗？
> 
> 仅在第一次访问时提示？或者修改`_0x27**cc`。

目前是切换网站时显示一次，大概5秒。 也算是第一次吧？

**Comment by miaomiaosoft** [comment]
建议去除，如果非要显示建议移到左/右下角，比如：
![image](https://github.com/netptop/siteproxy/assets/4084875/cecf4578-9167-40c0-9308-e5681f25379c)

文字尽量越少越好，具体的提示内容可以链接的方式跳转。
最好还是能自己配置是否显示。

另外新版本好像打开油管首页都显示为空的，之前的似乎没问题。

**Comment by netptop** [comment]
已经修改为24小时提示一次。
