### ISSUE TITLE
请问网站访问的时候无法显示图片是怎么原因

### ISSUE THREAD

**Issue by h00cker** [netptop/siteproxy#112]
通过容器部署的，一台vps正常，另外一台vps所有网站都无法显示图片，google访问显示：“Bad gateway Error code 502
”，请问有知道是啥原因的吗？多谢！

**Comment by netptop** [comment]
请确保配置文件里面的，是https，而不是http

**Comment by h00cker** [comment]
> 请确保配置文件里面的，是https，而不是http

感谢，没有注意这个。现在图片显示问题解决，访问google.com的时候出现如下问题，请教大佬可能什么原因，多谢！

Bad gateway Error code 502
Visit [cloudflare.com](https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_502&utm_campaign=read.brainvista.eu.org) for more information.
2024-08-05 10:34:46 UTC
You
Browser
Working
Los Angeles
[Cloudflare](https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_502&utm_campaign=read.brainvista.eu.org)
Working
read.brainvista.eu.org
Host
Error
What happened?
The web server reported a bad gateway error.

What can I do?
Please try again in a few minutes.

Cloudflare Ray ID: 8ae622f79f2d3125 • Your IP: Click to reveal xxx • Performance & security by [Cloudflare](https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_502&utm_campaign=read.brainvista.eu.org)

**Comment by netptop** [comment]
google禁止了cloudlfare IP访问。   请使用ipv6.google.com或者其他搜索引擎，默认主页里面有链接。
