### ISSUE TITLE
如何设置首页为某网站的代理

### ISSUE THREAD

**Issue by MCSeekeri** [netptop/siteproxy#28]
我想用siteproxy实现对某个站点的单独代理,同时代理外链及其它,所以能否设置打开部署后的域名就自动代理这个站点,不显示默认的起始页。
似乎代码中有类似设置,但Workers.js经过压缩我实在是找不到了（
如果Workers搞不定,能否提供其他部署方式的解决方案?

**Comment by AdamJohnson123** [comment]
直接反向代理那个网站就行了。
