### ISSUE TITLE
配合cdn使用的问题

### ISSUE THREAD

**Issue by zlj88** [netptop/siteproxy#4]
部署到vps后直接访问正常，套上cloudflare后可以访问首页，其它链接都显示{}

**Comment by netptop** [comment]
没有试过cloudflare, 暂时没有时间尝试.   欢迎定位解决问题并提交PR. 谢谢!

**Comment by netptop** [comment]
刚刚解决了套cloudflare问题. 请同步下代码.

**Comment by zlj88** [comment]
已解决
