### ISSUE TITLE
能不能部署到cloudflare上？

### ISSUE THREAD

**Issue by yingxueziqi** [netptop/siteproxy#5]

**Comment by netptop** [comment]
理论上可以, 欢迎提交PR, 补充cf部署说明.

**Comment by netptop** [comment]
Cf的serverless不是标准的.   它不支持node环境,  好多东西需要重构.   需要一段时间.

**Comment by netptop** [comment]
暂时没有时间搞。 欢迎各位提交PR。

**Comment by netptop** [comment]
已经支持。

**Comment by yingxueziqi** [comment]
自己搭建最好，独享。而且很简单，在我repo的build/worker.js中搜 Siteproxy.netptop.workers.dev  修改为你自己的子域名，然后把整个worker.js内容拷贝粘贴到你的worker里面，就OK了
来自开发者
