### ISSUE TITLE
这个代理挺不错就是部署到heroku速度慢

### ISSUE THREAD

**Issue by yoyling** [netptop/siteproxy#6]
访问方式简单，就是速度优点慢，而且上youtube会出现黄色警告：我们很快将停止支持此浏览器。要想获得最理想的体验，请更新您的浏览器。不知为什么为有这个。

**Comment by netptop** [comment]
youtube警告是因为代理时自动设置了user-agent为老版本浏览器.   原因是如果使用新版本user-agent, youtube就会用新版本js.   这在代理上会导致youtube加载异常.

**Comment by yoyling** [comment]
感谢，知道了，那速度问题怎么得到解决嘞。我试过cf+jsproxy，速度很快，但是每次都要到cf官网打开调试器，利用它自己生成的前缀访问外网。如果用正常的xxx.xxx.workers.dev就无法访问，会出现验证说你异常流量，然后验证一直失败。

**Comment by netptop** [comment]
把siteproxy部署到vps上, 然后套上cloudflare.   我就是这么做的.

**Comment by yoyling** [comment]
那我vps是阿里的1m的速度快嘛？还有就是vps的怎么套cloudflare？如果能TeamViewer帮我搞搞就好了

**Comment by netptop** [comment]
不知道阿里的vps怎么样.   请google下如何套cf.
