### ISSUE TITLE
无法使用Youtube

### ISSUE THREAD

**Issue by Liu233w** [netptop/siteproxy#62]
我把它部署到了 heroku 上，但是访问youtube视频的时候会提示 `Please update your browser`
<img width="1184" alt="Screen Shot 2022-06-23 at 1 48 27 pm" src="https://user-images.githubusercontent.com/16333687/175204862-16b329ca-c920-495b-b81d-322f68b4c571.png">

**Comment by frank-pian** [comment]
我看到首页上说只支持ff浏览器
有办法让chrome用上么

**Comment by netptop** [comment]
siteproxy2.0可以支持chrome，和手机播放youtube
