### ISSUE TITLE
用siteproxy下载Github文件到本地会导致文件sha256,md5等值跟原本的值不一样

### ISSUE THREAD

**Issue by Nuralii1i** [netptop/siteproxy#64]
我是个Archlinux用户，在下载aur软件时搭配siteproxy时发现，curl下载下来的源码包和许可证文件的sha256会跟PKGBUILD构建脚本里作者给定的值对不上，导致软件编译失败，经过多次尝试，确定会导致文件属性跟源文件不一致，望大佬修复

**Comment by Brx86** [comment]
这个是因为siteproxy会替换内容中的所有网址，对于文本类型的文件就很烦了，有些license下下来都变了。我的应对方法是只用siteproxy访问网页或克隆仓库（git clone 的话没问题，不会被替换），而需要下载文本文件时使用jsproxy或别的反代。
