### ISSUE TITLE
当在线游戏网站需要加载内核和ROM时，代理就会停止响应

### ISSUE THREAD

**Issue by palfans** [netptop/siteproxy#72]
比如通过代理访问 https://www.playemulator.io/gba-online/pokemon-x-and-y/, 可以正常显示页面，一旦点击游戏窗口的开始游戏按钮，就会一直停留在 downloading 界面，并且整个代理页面也停止响应。

**Comment by netptop** [comment]
测试了下， 不光是代理页面会停止响应， 整个浏览器都异常了。   这个看起来不是代理的问题。 从抓包看一切正常。 可能跟游戏的js有关。

**Comment by palfans** [comment]
可是如果直接访问这个链接，就能很顺利的运行rom。

**Comment by netptop** [comment]
这个游戏js， 会自动增加一个iframe， 设置跨域访问。 这时siteproxy会进行src替换，导致原来的request被cancel， 就这个动作就会导致游戏js不再正常，陷入死循环。 chrome挂死。 

这个问题基本无解。 单独对于该网站进行优化代价太大。 建议使用vpn玩这个游戏网站。

**Comment by palfans** [comment]
好的。感谢你的时间来分析问题。这个不是强需求，没有必要专门优化的。
