### ISSUE TITLE
部分中文网站有乱码

### ISSUE THREAD

**Issue by lgjssn** [netptop/siteproxy#74]
试了一下，有的网站会 锟斤拷
比如 bbs.nga.cn
主页面部分乱码，点进帖子的话，会全部乱码

**Comment by netptop** [comment]
GBK编码问题， 后面修改。

**Comment by AndersonGhost** [comment]
还是没有修复

**Comment by netptop** [comment]
是的，尚未修改。下个版本修改。

**Comment by netptop** [comment]
v2.1.16已经支持中文GBK编码。

**Comment by lgjssn** [comment]
试了一下，新版的确没有乱码了，但是登录却出现了问题。老版本可以正常输入账号密码验证码登录，新版走完流程会卡住，刷新也是未登录状态。

**Comment by netptop** [comment]
2.1.16之前的版本无法识别gbk，service worker无法工作。所以以前的版本基本无法运行。
你看到以前的版本可以正常登录，应该走的是你自己的ip，而不是通过代理登录的。
因为nga是国内网站，不用代理也能访问，不准备做登录适配。 除非需求很大。

**Comment by netptop** [comment]
可以的，以后可以尝试下NGA登录适配。 
 
不过你可以这么测试下， 使用2.1.12版本， 浏览器上按F12，打开network窗口，看看登录过程是否走的service worker， 按道理是无法走service worker的，因为gbk的原因，service worker无法插入，更别说工作了。

**Comment by lgjssn** [comment]
我试了一下不太清楚要具体看哪个条目。。
但是我们这里是不能直连的，另外我试了一下2.1.15也不能正常登录。我猜有可能不是因为2.1.16对gbk的支持带来的。

**Comment by netptop** [comment]
> 我试了一下不太清楚要具体看哪个条目。。 但是我们这里是不能直连的，另外我试了一下2.1.15也不能正常登录。我猜有可能不是因为2.1.16对gbk的支持带来的。

请尝试下v2.1.17看看是否解决了。

**Comment by lgjssn** [comment]
> > 我试了一下不太清楚要具体看哪个条目。。 但是我们这里是不能直连的，另外我试了一下2.1.15也不能正常登录。我猜有可能不是因为2.1.16对gbk的支持带来的。
> 
> 请尝试下v2.1.17看看是否解决了。

v2.1.17 成功登录了 
提示登录成功，唯一缺陷是不会像直连网站那样自动刷新跳转，可能跳转还有些问题；不过点击打开任意子页面就能成功显示登录信息，可以正常使用了。
感谢大佬！
