### ISSUE TITLE
cf worker 部署 youtub 背景音乐

### ISSUE THREAD

**Issue by ticks-tan** [netptop/siteproxy#78]
使用 cf 部署后，访问youtub网站总是有一个背景音乐在播放，且无法关闭，不知道其他人有不有遇到这情况。

- 系统：ArchLinux
- 浏览器：Chrome

**Comment by netptop** [comment]
浏览器地址右侧有一个音乐的图标，点击可以暂停。 好像chrome://flags里面有一个#global-media-controls-cast-start-stop， 我设置disable之后不起作用。 
搞不清怎么回事。 网上也有很多类似的问题。

**Comment by netptop** [comment]
请尝试下v2.1.17，应该解决了。

**Comment by ticks-tan** [comment]
好的

**Comment by ticks-tan** [comment]
确实可以了，辛苦大佬了(‾◡◝)
