### ISSUE TITLE
youtube和谷歌无限弹出是否允许cookie，bing会遣返国内cnbing

### ISSUE THREAD

**Issue by Akiiia** [netptop/siteproxy#79]
2.1.17
部署于cloudflare_worker
电脑端edge和chrome无痕模式下均出现，手机浏览器无此现象（小米自带/via）
<img width="857" alt="image" src="https://github.com/netptop/siteproxy/assets/74829345/fbc94227-b164-44cb-a8ce-6fbe7c7fc708">

**Comment by netptop** [comment]
非无痕模式是否有问题？   chrome怎么样？

**Comment by Akiiia** [comment]
> 非无痕模式是否有问题？ chrome怎么样？

电脑端edge和chrome无痕模式下均出现，反而手机浏览器无此现象（小米自带/via）

**Comment by StephenKingJJY** [comment]
遇到相同弹窗情况。
mac-safari电脑端没问题，ios下safari和via都会弹。

**Comment by netptop** [comment]
v2.1.18应该已经解决了这个问题。

**Comment by Akiiia** [comment]
> v2.1.18应该已经解决了这个问题。

非常感谢，不过我已经通过vps部署解决了这个问题
