### ISSUE TITLE
Twitter不可用，跳转回首页，带决解方案

### ISSUE THREAD

**Issue by Akiiia** [netptop/siteproxy#80]
域名多了/explore
首页导航的是 https://xxx/a/https/twitter.com/explore
会跳转回首页

https://xxx/a/https/twitter.com/ 是可以正确访问的

**Comment by Akiiia** [comment]
另附上telegram的bughttps://xxx/a/https/web.telegram.org

**Comment by netptop** [comment]
谢谢哈！

**Comment by netptop** [comment]
已经修改。
