### ISSUE TITLE
希望适配 devv.ai

### ISSUE THREAD

**Issue by Akiiia** [netptop/siteproxy#83]
![image](https://github.com/netptop/siteproxy/assets/74829345/d4383be6-f975-4812-a741-6ed631f5f2ac)

**Comment by netptop** [comment]
好的。

**Comment by Akiiia** [comment]
> 好的。

感谢

**Comment by netptop** [comment]
v2.2.0已经可以支持devv.ai了。

**Comment by Akiiia** [comment]
> v2.2.0已经可以支持devv.ai了。

![image](https://github.com/netptop/siteproxy/assets/74829345/d5ec68f9-d912-4418-acd5-4bdac7b61522)
（貌似并不）

**Comment by netptop** [comment]
试试v2.2.1, 如果还不行， 请发送网址和密码到netptop@gmail.com，我回头看看。

**Comment by Akiiia** [comment]
> 试试v2.2.1， 如果还不行， 请发送网址和密码到 [netptop@gmail.com](mailto:netptop@gmail.com)，我回头看看。

已发送

**Comment by netptop** [comment]
Cloudflare版本没有问题， 但是vps部署有问题。

**Comment by netptop** [comment]
请使用v2.2.3版本进行vps部署，注意node必须升级到v21或者以上版本。

**Comment by Akiiia** [comment]
> 请使用v2.2.3版本进行vps部署，注意node必须升级到v21或者以上版本。

是的，在升级node版本后，我已成功使用，非常感谢。
