### ISSUE TITLE
WebKit/Safari 适配

### ISSUE THREAD

**Issue by JustHollika** [netptop/siteproxy#84]
#24 同样的问题
Chrome和Firefox一切正常，Safari无法覆写超链接
service worker状态未知，console打印了log，但是在devtools里看不到sw
怀疑是混淆导致的，报错 Unhandled Promise Rejection: ReferenceError: Can't find variable: _0x5a10cf

替换_0x5a10cf为_0xc8de后重试，报错消失，又有了其他类似的报错..
![图片](https://github.com/netptop/siteproxy/assets/164742181/5fbb0823-1d97-46f5-81c9-40494bc6ddf1)
![图片](https://github.com/netptop/siteproxy/assets/164742181/ad23d71f-17bd-443f-8cca-5b08d461d0e6)

**Comment by netptop** [comment]
这个问题是： 刚开始打开浏览器，访问www.netptop.com，然后点击里面的网站链接，就出现的问题？ 
还是说，经过一番浏览之后， 然后回到www.netptop.com后，点击链接出现的？ 

v2.1.19以及之前的版本确实存在部分网站上点击链接，跳过代理的情况。

**Comment by JustHollika** [comment]
1、刚开始打开就会出现，而且所有的网站都会触发
2、已测试多个版本，包括vps和cf部署，均会触发
3、iOS上的所有浏览器都是webkit内核，均无法使用

**Comment by netptop** [comment]
是的，我确实在iphone上看到这个问题。 奇怪的是， 在macos上的safari没有这个问题。 
请问你是如何打开iphone 上safari的dev tools的？   现在主要是不知道怎么调试iphone。

**Comment by JustHollika** [comment]
> 是的，我确实在iphone上看到这个问题。 奇怪的是， 在macos上的safari没有这个问题。 请问你是如何打开iphone 上safari的dev tools的？ 现在主要是不知道怎么调试iphone。

其实我并没有macos设备，但我在browserstack的mac上能复现这个问题。
iOS的devtools可以在app store下载，搜索devtools会有Safari插件可以安装，然后在safari设置中启用即可

**Comment by netptop** [comment]
多谢！ 我回头试试。

**Comment by JustHollika** [comment]
谢谢大佬，本来不想麻烦大佬的 非JS技术栈，对着混淆debug实属无能为力，希望大佬早日修好orz

**Comment by netptop** [comment]
请试试v2.2.0

**Comment by JustHollika** [comment]
It works correctly! 谢谢大佬
