### ISSUE TITLE
征集www.netptop.com主页

### ISSUE THREAD

**Issue by netptop** [netptop/siteproxy#93]
由于本人的前端设计水平有限， 默认www.netptop.com主页被人诟病已久:)

现在征集默认主页页面设计，要求能直接部署在cf workers上。 请直接跟帖提供内容， 或者pull request提供。 或者email发送给netptop@gmail.com

采纳的网页将直接合入本repo

**Comment by lwd-temp** [comment]
推荐DDG：https://duckduckgo.com/?kae=-1&kp=-2&kn=1&k1=-1&kax=-1&kak=-1&kap=-1&kaq=-1&kao=-1&kau=-1&kc=-1&kg=p&k18=1

**Comment by Zding89** [comment]
https://github.com/WebStackPage/WebStackPage.github.io

推荐这个

**Comment by netptop** [comment]
别推荐了， PR行不？

**Comment by netptop** [comment]
请在cf_www.netptop.com_worker.js基础上提交PR。 谢谢 ！
